
import { ActivityLog } from "@/types";
import { supabase } from "@/lib/supabase";

export const activityService = {
    async log(userId: string, action: string, taskId?: string) {
        // We need the user's current session or profile ID. 
        // The service is usually called with userId from the caller.

        await supabase.from('activity_logs').insert({
            user_id: userId,
            action: action,
            details: taskId ? `Task ID: ${taskId}` : undefined,
            // timestamp auto-generated by db
        });
    },

    async getLogs(): Promise<ActivityLog[]> {
        const { data, error } = await supabase
            .from('activity_logs')
            .select('*')
            .order('timestamp', { ascending: false });

        if (error || !data) return [];

        return data.map((log: any) => ({
            id: log.id,
            userId: log.user_id,
            action: log.action,
            timestamp: log.timestamp,
            taskId: log.details?.replace('Task ID: ', '') || undefined
        }));
    }
};
